FROM alpine/curl:8.21.0@sha256:fd7f01bc6c6caec45a8fd5b871f0f51bf3c7cee0b185830ff25b8110f7e6e77d

ENV s5cmd_version=2.3.0
ENV kubectl_version=1.32.2
ENV s5cmd_url=https://github.com/peak/s5cmd/releases/download/v${s5cmd_version}/s5cmd_${s5cmd_version}_Linux-64bit.tar.gz
ENV kubectl_url=https://dl.k8s.io/release/v${kubectl_version}/bin/linux/amd64/kubectl

COPY ./extra/kubeconfig-reloader.sh /usr/local/bin/kubeconfig-reloader

RUN apk add --no-cache bash yq && \
    curl -Lo /tmp/s5cmd.tar.gz ${s5cmd_url} && \
    tar -xzf /tmp/s5cmd.tar.gz -C /usr/local/bin && \
    rm /tmp/s5cmd.tar.gz && \
    curl -Lo /usr/local/bin/kubectl ${kubectl_url} && \
    chmod +x /usr/local/bin/s5cmd /usr/local/bin/kubeconfig-reloader /usr/local/bin/kubectl

ENTRYPOINT ["/usr/local/bin/kubeconfig-reloader"]
