FROM alpine/curl:8.14.1@sha256:468f799a9d01c3ffb0dd9d612e89f414af5eac3a58b1877e221451ce5a0639c9

ENV s5cmd_version=2.3.0
ENV kubectl_version=1.32.2
ENV s5cmd_url=https://github.com/peak/s5cmd/releases/download/v${s5cmd_version}/s5cmd_${s5cmd_version}_Linux-64bit.tar.gz
ENV kubectl_url=https://dl.k8s.io/release/v${kubectl_version}/bin/linux/amd64/kubectl

COPY ./extra/kubeconfig-reloader.sh /usr/local/bin/kubeconfig-reloader

RUN apk add --no-cache bash yq && \
    curl -Lo /tmp/s5cmd.tar.gz ${s5cmd_url} && \
    tar -xzf /tmp/s5cmd.tar.gz -C /usr/local/bin && \
    rm /tmp/s5cmd.tar.gz && \
    curl -Lo /usr/local/bin/kubectl ${kubectl_url} && \
    chmod +x /usr/local/bin/s5cmd /usr/local/bin/kubeconfig-reloader /usr/local/bin/kubectl

ENTRYPOINT ["/usr/local/bin/kubeconfig-reloader"]
