{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "keess.fullname" . }}
  labels:
    {{- include "keess.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "keess.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "keess.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
