apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keess.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keess.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "keess.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keess.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keess.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: config
        secret:
          secretName: {{ template "keess.fullname" . }}
          defaultMode: 420
      containers:
        - name: {{ .Chart.Name }}
          args:
            - --logLevel={{ .Values.logLevel }}
            - --localCluster={{ .Values.localCluster }}
            {{- if .Values.remoteClusters }}
            {{- range .Values.remoteClusters }}
            - --remoteCluster={{ . }}
            {{- end }}
            {{- end }}            
            - --kubeConfigPath={{ .Values.kubeConfigPath }}
            - --pollingInterval={{ .Values.pollingInterval }}
            - --namespacePollingInterval={{ .Values.namespacePollingInterval }}
            - --housekeepingInterval={{ .Values.housekeepingInterval }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config
            mountPath: /root/.kube
            readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
