{{- if and .Values.kubeconfigReloader.enabled .Values.kubeconfigReloader.credentials.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubeconfigReloader.credentials.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keess.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.kubeconfigReloader.credentials.data | nindent 2 }}
{{- end }}
