apiVersion: v1
kind: Service
metadata:
  name: {{ include "keess.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keess.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/path: "/metrics"
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "keess.selectorLabels" . | nindent 4 }}
