{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keess.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keess.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.createToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keess.serviceAccountName" . }}-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "keess.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
{{- end }}
