# Example: ConfigMap Synchronization with Keess
# This example shows how to sync a ConfigMap to labeled destination namespaces
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: test-keess
  labels:
    keess.powerhrg.com/sync: "namespace"
  annotations:
    keess.powerhrg.com/namespace-label: keess.powerhrg.com/test-sync-dest="true
data:
  test: "namespace sync works!"

